server:
  port: 8082
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:13306/weblog?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    username: root
    password: hcs@2023
    hikari:
      idle-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      pool-name: weblog-HikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: select 1



mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml



