server:
  port: 8081
spring:
  profiles:
    active: dev
  servlet:
    multipart:
      max-file-size: 10MB

logging:
  config: classpath:logback-weblog.xml

weblog:
  security:
    jwt:
      secret-key: JDJhJDEwJDVsN0l5SkM3ekFobU52Q0QzdVhaTHVyVkE1dU91VXYuVmVyanRqSXdSOThWbmVoc3ZaZ1NT
      expires: 360000
  minio:
    endpoint: http://localhost:9000
    access-key: admin
    secret-key: admin1234
    bucket-name: weblog
