server:
  port: 8081
spring:
  profiles:
    active: dev

logging:
  config: classpath:logback-weblog.xml

weblog:
  security:
    jwt:
      secret-key: JDJhJDEwJDVsN0l5SkM3ekFobU52Q0QzdVhaTHVyVkE1dU91VXYuVmVyanRqSXdSOThWbmVoc3ZaZ1NT
      expires: 3600
